[package]
name = "OrpheusCore"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
winapi = { version = "0.3", features = ["wincon", "winuser", "libloaderapi", "commctrl", "wingdi"] }
warp = "0.3"
tokio = { version = "1", features = ["full"] }
serde_json = "1"
serde = { version = "1", features = ["derive"] }
janus_log_nucleus = { path = "../nucleus/janus_log_nucleus" }
janus_config_nucleus = { path = "../nucleus/janus_config_nucleus" }
janus_platform_nucleus = { path = "../nucleus/janus_platform_nucleus" }
janus_logwindow_nucleus = { path = "../nucleus/janus_logwindow_nucleus" }
janus_stream_nucleus = { path = "../nucleus/janus_stream_nucleus" }
janus_synth_nucleus = { path = "../nucleus/janus_synth_nucleus" }

[build-dependencies]
winres = "0.1"
