[package]
name = "janus_nucleus"
version = "0.1.0"
edition = "2021"

[dependencies]
winapi = { version = "0.3", features = ["wincon", "winuser", "libloaderapi", "commctrl", "wingdi"] }
widestring = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ebur128 = "0.1"
rodio = "0.17"
