[package]
name = "JanusCore"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
winapi = { version = "0.3", features = ["wincon", "winuser", "libloaderapi", "commctrl", "wingdi"] }
rodio = "0.17"
warp = "0.3"
tokio = { version = "1", features = ["full"] }
serde_json = "1"
serde = { version = "1", features = ["derive"] }
futures = "0.3.31"
janus_log_nucleus = { path = "../nucleus/janus_log_nucleus" }
janus_config_nucleus = { path = "../nucleus/janus_config_nucleus" }
janus_platform_nucleus = { path = "../nucleus/janus_platform_nucleus" }
janus_logwindow_nucleus = { path = "../nucleus/janus_logwindow_nucleus" }
janus_library_nucleus = { path = "../nucleus/janus_library_nucleus" }
janus_playlist_nucleus = { path = "../nucleus/janus_playlist_nucleus" }

[build-dependencies]
winres = "0.1"