[package]
name = "JanusCore"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
winapi = { version = "0.3", features = ["wincon", "winuser", "libloaderapi", "commctrl", "wingdi"] }
rodio = "0.17"
walkdir = "2.4"
rand = "0.8"
warp = "0.3"
tokio = { version = "1", features = ["full"] }
serde_json = "1"
serde = { version = "1", features = ["derive"] }
reqwest = { version = "0.11", features = ["blocking"] }
symphonia = { version = "0.5", features = ["mp3", "wav", "flac", "aac", "isomp4"] }
futures = "0.3.31"
base64 = "0.21"
janus_nucleus = { path = "../janus_nucleus" }

[build-dependencies]
winres = "0.1"